language: node_js
node_js:
  - "0.10"

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq genext2fs qemu-system-arm qemu-system-x86
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi

install:
  - JOBS=1 npm run BigRedButton

before_script:
  - cd node_modules/nodeos-barebones && npm install NodeOS/node-suppose#patch-1
